version: '3'

services:
  app:
    container_name: BillingApp
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8100:8100"
    command: >
      sh -c "python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8100"
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: BillingDB
    restart: always
    environment:
      MYSQL_DATABASE: bills
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 33066:3306
    volumes:
      - .dbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: BillingAdminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./adminer/:/adminer/
    depends_on:
      - db



      
