version: '3'

services:
  app:
    container_name: BillingApp
    build:
      context: .
      dockerfile: ./app
    volumes:
      - ./app:/app
    ports:
      - "8100:8100"
    command: >
      sh -c "python -m pip install --upgrade pip &&
        pip install -r requirements.txt
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8100"
    depends_on:
      - db
    networks:
      billing:
        ipv4_address: 192.168.92.21

  db:
    image: mariadb:10.5
    container_name: BillingDB
    restart: always
    environment:
      MYSQL_DATABASE: bills
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 33066:3306
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      billing:
        ipv4_address: 192.168.92.22

  adminer:
    image: adminer
    container_name: BillingAdminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./adminer/:/adminer/
    depends_on:
      - db
    networks:
      billing:
        ipv4_address: 192.168.92.23

networks:
  billing:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"