version: '3'

services:
  app:
    container_name: BillingApp
    build: ./app
    volumes:
      - static:/static
    env_file:
      - ./app/.env
    command: >
      sh -c "python manage.py collectstatic --no-input"

    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      billing:
        ipv4_address: 192.168.92.21

  proxy:
    container_name: BillingProxy
    build: ./proxy
    volumes:
      - static:/static
    ports:
      - "8001:80"
    depends_on:
      - app
    networks:
      billing:
        ipv4_address: 192.168.92.22
  
  db:
    image: mariadb:10.5
    container_name: BillingDB
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "8002:3306"
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      billing:
        ipv4_address: 192.168.92.23

  adminer:
    image: adminer
    container_name: BillingAdminer
    restart: always
    ports:
      - 8003:8080
    volumes:
      - ./adminer/:/adminer/
    depends_on:
      - db
    networks:
      billing:
        ipv4_address: 192.168.92.24

volumes:
  .dbdata:
  static:

networks:
  billing:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
